matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      install:
        - sudo apt install git -y
        - pip3 install -U "git+https://github.com/zero-os/0-core.git@${core_0_branch}#subdirectory=client/py-client"
        - pip3 install -U "git+https://github.com/zero-os/0-orchestrator.git@${orchestrator_branch}#subdirectory=pyclient"
        - curl -s https://install.zerotier.com/ | sudo bash
        - pip3 install -r test/deploy_test_env/requirements.txt
      before_script:
        - bash test/deploy_test_env/run_tests.sh before
      script:
        - bash test/deploy_test_env/run_tests.sh test $TEST_CASE
      after_script:
        - bash test/deploy_test_env/run_tests.sh after

    - language: go
      sudo: true
      dist: trusty
      go: 1.8
      install: skip
      script:
        - make
        - make test

    - language: go
      sudo: true
      dist: trusty
      go: 1.9
      install: skip
      script:
        - make
        - make test

    - language: go
      sudo: true
      dist: trusty
      go: 1.9
      install: skip
      script: make testcov
      after_success: bash <(curl -s https://codecov.io/bash) -F unittests

    - language: go
      go: 1.9
      install: skip
      script:
        - go vet $(go list ./... | grep -v vendor)
        - diff -u <(echo -n) <(gofmt -d $(find . -name "*\.go" | grep -v '\.git/' | grep -v vendor))

    - language: go
      sudo: true
      dist: trusty
      go: 1.9
      install: skip
      script: make testserverrace

    - language: go
      sudo: true
      dist: trusty
      go: 1.9
      install: skip
      script: make testclientrace

    - language: go
      sudo: true
      dist: trusty
      go: 1.9
      install:
        - ./utils/scripts/install_capnp_unix.sh
        - ./utils/scripts/install_protoc_unix.sh
      script: make testcodegen
